In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import Binarizer
from sklearn.compose import ColumnTransformer

In [11]:
df = pd.read_csv(r"C:\Users\gsksd\Downloads\train.csv",usecols=['Age','Fare','SibSp','Parch','Survived'])

In [12]:
df.sample(5)

     Survived   Age  SibSp  Parch    Fare
12          0  20.0      0      0    8.05
390         1  36.0      1      2  120.00
812         0  35.0      0      0   10.50
635         1  28.0      0      0   13.00
423         0  28.0      1      1   14.40

In [13]:
df.dropna(inplace=True)

In [14]:
df.shape

(714, 5)

In [15]:
df['family'] = df['SibSp'] + df['Parch']

In [16]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [ ]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [17]:
df.sample(5)

     Survived   Age     Fare  family
70          0  32.0  10.5000       0
206         0  32.0  15.8500       1
824         0   2.0  39.6875       5
271         1  25.0   0.0000       0
746         0  16.0  20.2500       2

In [19]:
trf = ColumnTransformer(
    [
        ('bin' , Binarizer(copy=False) ,['family'])
    ]
)