In [28]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv(r"C:\Users\gsksd\Downloads\cars.csv")

In [3]:
df.sample(5)

         brand  km_driven    fuel         owner  selling_price
6344    Maruti      60000  Petrol  Second Owner         300000
3745    Maruti      87000  Diesel   First Owner         459999
6328      Ford     163000  Diesel   First Owner         200000
2763   Hyundai      57000  Petrol   First Owner         200000
7466  Mahindra     110000  Diesel  Second Owner         370000

In [5]:
df.shape

(8128, 5)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [11]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [12]:
df['brand'].nunique()

32

In [13]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [15]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## 1. OneHotEncoding using Pandas

In [16]:
pd.get_dummies(df , columns=['fuel' , 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## (K-1) OHE

In [20]:
pd.get_dummies(df , columns=['fuel' , 'owner'],drop_first= True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

#### but we cannot use pandas to perform One Hot Encoding , because pandas doesnot remember the columns data ...
#### we have to use SCIKIT learn to perform OHE

## Train Test Split

In [22]:
X = df.iloc[:,0:4]

In [23]:
y = df.iloc[:,-1]

In [24]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=2)

In [26]:
X_train.head()

        brand  km_driven    fuel                 owner
582   Hyundai      76000  Petrol  Fourth & Above Owner
133    Jaguar      45000  Diesel           First Owner
3535     Tata     100000  Diesel           First Owner
2890   Maruti     120000  Diesel          Second Owner
963    Toyota     110000  Diesel          Second Owner

In [27]:
y_train.head()

582      210000
133     3200000
3535     400000
2890     600000
963      910000
Name: selling_price, dtype: int64

## one hot encoding using Scikit learn

In [84]:

ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [86]:
X_train_new =ohe.fit_transform(X_train[['fuel' , 'owner']])
X_test_new =ohe.transform(X_test[['fuel' , 'owner']])

In [87]:
X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(6096, 7), dtype=int32)

In [88]:
X_train_new.shape

(6096, 7)

In [97]:
np.hstack((X_train[['brand' , 'km_driven']].values , X_train_new)).shape

(6096, 9)

In [90]:
counts = df['brand'].value_counts()

In [91]:
df['brand'].nunique
threshold = 100

In [92]:
counts[counts <= threshold].index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [93]:
repl = counts[counts <= threshold].index

In [116]:
brand_ohe = pd.get_dummies(X_train['brand'].replace(repl, 'uncommon'), dtype=np.int32)

In [109]:
fuel_owner_ohe = pd.DataFrame(X_train_new,columns=ohe.get_feature_names_out(['fuel', 'owner']),index=X_train.index
)

In [100]:
remaining = X_train[['km_driven']]

In [104]:
X_final = pd.concat([
    X_train[['km_driven']].reset_index(drop=True),
    brand_ohe.reset_index(drop=True),
    fuel_owner_ohe.reset_index(drop=True)
], axis=1)

In [110]:
fuel_owner_ohe = fuel_owner_ohe.reset_index(drop=True)
brand_ohe = brand_ohe.reset_index(drop=True)
remaining = X_train[['km_driven']].reset_index(drop=True)

In [111]:
X_final = pd.concat(
    [remaining, brand_ohe, fuel_owner_ohe],
    axis=1
)

In [112]:
print(X_final.head())
print(X_final.isnull().sum().sum())

   km_driven  BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
0      76000    0          0     0      0        1         0       0        0
1      45000    0          0     0      0        0         0       0        0
2     100000    0          0     0      0        0         0       0        0
3     120000    0          0     0      0        0         0       1        0
4     110000    0          0     0      0        0         0       0        0

   Skoda  ...  Toyota  Volkswagen  uncommon  fuel_Diesel  fuel_LPG  \
0      0  ...       0           0         0            0         0
1      0  ...       0           0         1            1         0
2      0  ...       0           0         0            1         0
3      0  ...       0           0         0            1         0
4      0  ...       1           0         0            1         0

   fuel_Petrol  owner_Fourth & Above Owner  owner_Second Owner  \
0            1                           1                   0
1            0                           0                   0
2            0                           0                   0
3            0                           0                   1
4            0                           0                   1

   owner_Test Drive Car  owner_Third Owner
0                     0                  0
1                     0                  0
2                     0                  0
3                     0                  0
4                     0                  0

[5 rows x 21 columns]
0

In [115]:
X_final.to_csv("feature_engineered_data1.csv", index=False)